name: listdeps

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: test
    steps:
    - name: test
      id: testROC  #Failed to download action 'https://api.github.com/repos/actions/vjcitn/tarball/master'. 
      uses: listdeps/actions@master
      with: 
        pkg-to-get-deps: 'ROC'
    - name: getlist
      run: echo "got ${{ steps.testROC.deps }}"
 
