name: listdeps

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: testdocker
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: test_getdeps
      id: test_getdeps
      uses: vjcitn/listdeps@master
      with: 
        pkg-to-get-deps: 'ROC'
    - name: getjson
      uses: actions/upload-artifact@v1
      with:
        name: get_deps
        path: deps.json
 
