name: listdeps

on:[pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: testdocker2
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: test_getdeps
      id: test_getdeps
      uses: vjcitn/listdeps@master
      with: # PR SHOULD ADD VALUE BELOW
        pkg-to-get-deps: 
    - name: getjson
      uses: actions/upload-artifact@v1
      with:
        name: get_deps
        path: deps.json
 
